// This file is auto-generated by Supabase. Run generate_typescript_types after migrations.
// Placeholder until first generation.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      warehouses: {
        Row: {
          id: string
          code: string
          name: string
          active: boolean
        }
        Insert: {
          id?: string
          code: string
          name: string
          active?: boolean
        }
        Update: {
          id?: string
          code?: string
          name?: string
          active?: boolean
        }
      }
      suppliers: {
        Row: {
          id: string
          code: string
          name: string
          active: boolean
        }
        Insert: {
          id?: string
          code: string
          name: string
          active?: boolean
        }
        Update: {
          id?: string
          code?: string
          name?: string
          active?: boolean
        }
      }
      supplier_accounts: {
        Row: {
          id: string
          username: string
          password_hash: string
          full_name: string
          supplier_code_requested: string
          supplier_id: string | null
          status: 'pending' | 'active' | 'rejected'
          reject_reason: string | null
          created_at: string
          approved_at: string | null
        }
        Insert: {
          id?: string
          username: string
          password_hash: string
          full_name: string
          supplier_code_requested: string
          supplier_id?: string | null
          status?: 'pending' | 'active' | 'rejected'
          reject_reason?: string | null
          created_at?: string
          approved_at?: string | null
        }
        Update: {
          id?: string
          username?: string
          password_hash?: string
          full_name?: string
          supplier_code_requested?: string
          supplier_id?: string | null
          status?: 'pending' | 'active' | 'rejected'
          reject_reason?: string | null
          created_at?: string
          approved_at?: string | null
        }
      }
      bookings: {
        Row: {
          id: string
          booking_code: string
          booking_token: string
          supplier_account_id: string
          supplier_id: string
          warehouse_id: string
          delivery_date: string
          time_slot: '07-09' | '09-11' | '13-15' | '15-17'
          ghi_chu: string | null
          delivery_note: string
          nhanh_draft_bill_id: string | null
          status: Database['public']['Enums']['booking_status']
          submitted_at: string
          confirmed_by: string | null
          confirmed_at: string | null
          received_by: string | null
          received_at: string | null
        }
        Insert: {
          id?: string
          booking_code?: string
          booking_token?: string
          supplier_account_id: string
          supplier_id: string
          warehouse_id: string
          delivery_date?: string
          time_slot: '07-09' | '09-11' | '13-15' | '15-17'
          ghi_chu?: string | null
          delivery_note: string
          nhanh_draft_bill_id?: string | null
          status?: Database['public']['Enums']['booking_status']
          submitted_at?: string
          confirmed_by?: string | null
          confirmed_at?: string | null
          received_by?: string | null
          received_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bookings']['Insert']>
      }
      booking_items: {
        Row: {
          id: string
          booking_id: string
          product_code: string
          process_code: string
          delivery_round: number
          is_final_round: boolean
          mau: string | null
          quantity_booked: number
          quantity_received: number | null
          reviewed_at: string | null
          size_2xl_32: number
          size_3xl_33: number
          size_l_30: number
          size_m_29: number
          size_s_28: number
          size_xl_31: number
          status: Database['public']['Enums']['booking_item_status']
          total_quantity: number
          vat_invoice_url: string | null
          warehouse_code: string | null
          reject_reason: string | null
        }
        Insert: {
          id?: string
          booking_id: string
          product_code: string
          process_code: string
          delivery_round: number
          is_final_round?: boolean
          mau?: string | null
          quantity_booked: number
          quantity_received?: number | null
          reviewed_at?: string | null
          size_2xl_32?: number
          size_3xl_33?: number
          size_l_30?: number
          size_m_29?: number
          size_s_28?: number
          size_xl_31?: number
          status?: Database['public']['Enums']['booking_item_status']
          total_quantity?: number
          vat_invoice_url?: string | null
          warehouse_code?: string | null
          reject_reason?: string | null
        }
        Update: Partial<Database['public']['Tables']['booking_items']['Insert']>
      }
      booking_item_photos: {
        Row: {
          id: string
          booking_item_id: string
          storage_path: string
          photo_type: Database['public']['Enums']['photo_type']
          uploaded_at: string
        }
        Insert: {
          id?: string
          booking_item_id: string
          storage_path: string
          photo_type: Database['public']['Enums']['photo_type']
          uploaded_at?: string
        }
        Update: Partial<Database['public']['Tables']['booking_item_photos']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          recipient_type: 'supplier_account' | 'staff'
          recipient_id: string
          event_type: string
          message: string
          booking_id: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          recipient_type: 'supplier_account' | 'staff'
          recipient_id: string
          event_type: string
          message: string
          booking_id?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
      discrepancy_log: {
        Row: {
          id: string
          booking_item_id: string
          quantity_booked: number
          quantity_received: number
          difference: number
          notes: string | null
          recorded_at: string
        }
        Insert: {
          id?: string
          booking_item_id: string
          quantity_booked: number
          quantity_received: number
          difference?: number
          notes?: string | null
          recorded_at?: string
        }
        Update: Partial<Database['public']['Tables']['discrepancy_log']['Insert']>
      }
      booking_amendments: {
        Row: {
          id: string
          booking_id: string
          requested_by: string
          amendment_type: string
          proposed_changes: Json | null
          request_note: string
          status: 'pending' | 'approved' | 'denied'
          reviewer_note: string | null
          created_at: string
          resolved_at: string | null
        }
        Insert: {
          id?: string
          booking_id: string
          requested_by: string
          amendment_type?: string
          proposed_changes?: Json | null
          request_note: string
          status?: 'pending' | 'approved' | 'denied'
          reviewer_note?: string | null
          created_at?: string
          resolved_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['booking_amendments']['Insert']>
      }
      product_process_catalog: {
        Row: {
          id: string
          lark_record_id: string
          product_name: string
          order_code: string
          warehouse_code: string | null
          mau: string | null
          order_date: string | null
          total_quantity: number
          size_s_28: number
          size_m_29: number
          size_l_30: number
          size_xl_31: number
          size_2xl_32: number
          size_3xl_33: number
          active: boolean
          last_synced_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lark_record_id: string
          product_name: string
          order_code: string
          warehouse_code?: string | null
          mau?: string | null
          order_date?: string | null
          total_quantity?: number
          size_s_28?: number
          size_m_29?: number
          size_l_30?: number
          size_xl_31?: number
          size_2xl_32?: number
          size_3xl_33?: number
          active?: boolean
          last_synced_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['product_process_catalog']['Insert']>
      }
    }
    Views: {
      daily_capacity: {
        Row: {
          delivery_date: string
          total_bookings: number
          confirmed_items: number
          confirmed_units: number
        }
      }
    }
    Functions: Record<string, never>
    Enums: {
      account_status: 'pending' | 'active' | 'rejected'
      booking_status: 'pending' | 'partially_approved' | 'partially_rejected' | 'confirmed' | 'rejected' | 'returned' | 'received' | 'cancelled'
      booking_item_status: 'pending' | 'confirmed' | 'rejected' | 'returned'
      time_slot: '07-09' | '09-11' | '13-15' | '15-17'
      photo_type: 'delivery_slip' | 'discrepancy' | 'vat_invoice'
      notification_recipient: 'supplier_account' | 'staff'
    }
  }
}
